### ISSUE TITLE
1.1 Post a Look

### ISSUE THREAD

**Issue by a-havard** [a-havard/LookShare#10]
Description: As a user, I want to publish a makeup look to my feed so that I can share with the rest of my followers what I'm using for my makeup look.

Acceptance Criteria:
Given I want to post a makeup look, when the "post" button is pressed on my dashboard, then I will be prompted to submit a post with all the relevant information (photo, products, instructions, kind of look).
Given I have already pressed the "post" button, when I press the "add photo" button, then I can select a photo to add to my post.
Given I have entered all of the relevant information about my post, when I press the "submit" button, then my post will be shared with my followers.

**Comment by Will-Dunn** [comment]
I just did a little bit of planning for how to get this working at least for the front end, all the information they are inputting in creating the post can be gotten from a form with an input field for the picture, 2 text areas for products and instructions, and maybe a select field for kind of look.

**Comment by n-wes** [comment]
Will have mockups for posting by thursdat afternoon.
