### ISSUE TITLE
1.3 Makeup Look Instructions

### ISSUE THREAD

**Issue by a-havard** [a-havard/LookShare#7]
Description: As a user, I want to include instructions for how I did my makeup look so that my followers can replicate my makeup look.

Acceptance Criteria:
Given I have pressed the "post" button, when I press the "add instructions" button, then I will be prompted with a text entry box so I can type in the instructions.
Given that I have pressed "add instructions", when I enter a text entry, then I will be limited to 500 characters.

**Comment by Will-Dunn** [comment]
done
